import type {
  Trainer,
  Course,
  Organization,
  TrainerDashboardKPIs,
  OrganizationDashboardKPIs,
  UpcomingSession,
  ActivityItem,
  MonthlyRevenuePoint,
  MonthlySpendingPoint,
  UpcomingTraining,
  TrainerProfileStats,
  Annonce,
  TrainerAvailability,
  TrainerAccountSettings,
  TrainerSupportData,
} from "@/types";

export const trainers: Trainer[] = [
  {
    id: "t1",
    name: "Vanessa Martin",
    bio: "Formatrice en management et leadership avec 10 ans d'expérience en entreprise. Spécialisée dans la conduite du changement.",
    specialties: ["LeaderShip", "Management Participatif", "Conduite du changement", "Communication", "Cohésion d'équipe"],
    city: "Montpellier",
    departement: "Hérault",
    departementNum: "34",
    domain: "Management",
    interventionType: "Présentiel",
    expertiseLevel: "Expert",
    availableFrom: "2025-10-12",
    yearsOfExperience: 8,
    hourlyRate: 80,
    rating: 4.9,
    reviewCount: 87,
    avatar: "/placeholder-avatar.png",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=700&fit=crop&crop=face",
  },
  {
    id: "t2",
    name: "Patrick Dubois",
    bio: "Expert IA et automatisation. Ancien lead data scientist chez un grand groupe tech. Certifié TensorFlow et Azure AI.",
    specialties: ["Automatisation", "Machine Learning", "Python", "Deep Learning", "NLP", "Computer Vision", "MLOps"],
    city: "Lyon",
    departement: "Rhône",
    departementNum: "69",
    domain: "IA",
    interventionType: "Hybride",
    expertiseLevel: "Expert",
    availableFrom: null,
    yearsOfExperience: 12,
    hourlyRate: 124,
    rating: 4.8,
    reviewCount: 64,
    avatar: "/placeholder-avatar.png",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=700&fit=crop&crop=face",
  },
  {
    id: "t3",
    name: "Amina Benali",
    bio: "UX/UI Designer passionnée par l'accessibilité et le design system. 8 ans d'expérience en agence et freelance.",
    specialties: ["Figma", "UX Research", "Design System", "Accessibilité", "Prototypage"],
    city: "Bordeaux",
    departement: "Gironde",
    departementNum: "33",
    domain: "Digital",
    interventionType: "Distanciel",
    expertiseLevel: "Expert",
    availableFrom: null,
    yearsOfExperience: 8,
    hourlyRate: 95,
    rating: 4.7,
    reviewCount: 52,
    avatar: "/placeholder-avatar.png",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&h=700&fit=crop&crop=face",
  },
  {
    id: "t4",
    name: "Thomas Leroy",
    bio: "DevOps engineer et formateur certifié Kubernetes. Accompagne les équipes dans leur transition cloud native.",
    specialties: ["Docker", "Kubernetes", "CI/CD", "Terraform", "AWS"],
    city: "Nantes",
    departement: "Loire-Atlantique",
    departementNum: "44",
    domain: "Digital",
    interventionType: "Hybride",
    expertiseLevel: "Expert",
    availableFrom: "2025-11-01",
    yearsOfExperience: 10,
    hourlyRate: 140,
    rating: 4.9,
    reviewCount: 41,
    avatar: "/placeholder-avatar.png",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&h=700&fit=crop&crop=face",
  },
  {
    id: "t5",
    name: "Claire Fontaine",
    bio: "Consultante marketing digital spécialisée en growth hacking et SEO technique.",
    specialties: ["SEO", "Google Ads", "Analytics", "Growth Hacking"],
    city: "Toulouse",
    departement: "Haute-Garonne",
    departementNum: "31",
    domain: "Marketing",
    interventionType: "Distanciel",
    expertiseLevel: "Intermédiaire",
    availableFrom: null,
    yearsOfExperience: 5,
    hourlyRate: 85,
    rating: 4.6,
    reviewCount: 73,
    avatar: "/placeholder-avatar.png",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&h=700&fit=crop&crop=face",
  },
  {
    id: "t6",
    name: "Julien Moreau",
    bio: "Coach agile et formateur en management. Certifié SAFe et Scrum Master. Accompagne les transformations organisationnelles.",
    specialties: ["Scrum", "SAFe", "Management Agile", "Leadership"],
    city: "Lille",
    departement: "Nord",
    departementNum: "59",
    domain: "Management",
    interventionType: "Présentiel",
    expertiseLevel: "Expert",
    availableFrom: "2025-12-15",
    yearsOfExperience: 9,
    hourlyRate: 110,
    rating: 4.8,
    reviewCount: 96,
    avatar: "/placeholder-avatar.png",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&h=700&fit=crop&crop=face",
  },
];

export const courses: Course[] = [
  {
    id: "c1",
    title: "React Avancé — Patterns et Performance",
    description:
      "Maîtrisez les patterns avancés de React : hooks personnalisés, render props, compound components et optimisation des performances.",
    price: 890,
    duration: "3 jours",
    category: "DEVELOPMENT",
    status: "PUBLISHED",
    trainerId: "t1",
    trainerName: "Sophie Martin",
    enrollmentCount: 124,
    image: "/placeholder-course.png",
  },
  {
    id: "c2",
    title: "Machine Learning pour les entreprises",
    description:
      "Introduction pratique au ML pour décideurs et développeurs. De la donnée au modèle déployé en production.",
    price: 1200,
    duration: "5 jours",
    category: "DATA",
    status: "PUBLISHED",
    trainerId: "t2",
    trainerName: "Marc Dubois",
    enrollmentCount: 89,
    image: "/placeholder-course.png",
  },
  {
    id: "c3",
    title: "Design System — Créer et maintenir",
    description:
      "Apprenez à concevoir, documenter et faire vivre un design system pérenne avec Figma et Storybook.",
    price: 650,
    duration: "2 jours",
    category: "DESIGN",
    status: "PUBLISHED",
    trainerId: "t3",
    trainerName: "Amina Benali",
    enrollmentCount: 67,
    image: "/placeholder-course.png",
  },
  {
    id: "c4",
    title: "Kubernetes en production",
    description:
      "Déployer, monitorer et scaler vos applications sur Kubernetes. Inclut Helm, Istio et observabilité.",
    price: 1500,
    duration: "4 jours",
    category: "DEVOPS",
    status: "PUBLISHED",
    trainerId: "t4",
    trainerName: "Thomas Leroy",
    enrollmentCount: 45,
    image: "/placeholder-course.png",
  },
  {
    id: "c5",
    title: "SEO technique pour développeurs",
    description:
      "Comprendre et implémenter le SEO technique : performance web, données structurées, Core Web Vitals.",
    price: 490,
    duration: "2 jours",
    category: "MARKETING",
    status: "PUBLISHED",
    trainerId: "t5",
    trainerName: "Claire Fontaine",
    enrollmentCount: 156,
    image: "/placeholder-course.png",
  },
  {
    id: "c6",
    title: "Leadership agile pour managers",
    description:
      "Transformez votre management avec les principes agiles. Facilitation, feedback, et organisation apprenante.",
    price: 780,
    duration: "3 jours",
    category: "MANAGEMENT",
    status: "PUBLISHED",
    trainerId: "t6",
    trainerName: "Julien Moreau",
    enrollmentCount: 203,
    image: "/placeholder-course.png",
  },
  {
    id: "c7",
    title: "Next.js 16 — Server Components et App Router",
    description:
      "Découvrez les dernières fonctionnalités de Next.js : Server Components, streaming, server actions et déploiement edge.",
    price: 950,
    duration: "3 jours",
    category: "DEVELOPMENT",
    status: "DRAFT",
    trainerId: "t1",
    trainerName: "Sophie Martin",
    enrollmentCount: 0,
    image: "/placeholder-course.png",
  },
  {
    id: "c8",
    title: "Architecture microservices avec Node.js",
    description:
      "Concevoir et implémenter une architecture microservices robuste avec Node.js, RabbitMQ et Docker.",
    price: 1100,
    duration: "4 jours",
    category: "DEVELOPMENT",
    status: "DRAFT",
    trainerId: "t1",
    trainerName: "Sophie Martin",
    enrollmentCount: 0,
    image: "/placeholder-course.png",
  },
];

export const organizations: Organization[] = [
  {
    id: "o1",
    name: "TechCorp Formation",
    description:
      "Organisme de formation spécialisé dans les métiers du numérique. Certifié Qualiopi.",
    logo: "/placeholder-logo.png",
    city: "Paris",
    employeeCount: 45,
  },
  {
    id: "o2",
    name: "FormaPro Institute",
    description:
      "Centre de formation continue pour les entreprises. Plus de 200 formations au catalogue.",
    logo: "/placeholder-logo.png",
    city: "Lyon",
    employeeCount: 120,
  },
  {
    id: "o3",
    name: "Digital Academy",
    description:
      "Accélérateur de compétences digitales pour les équipes en transformation.",
    logo: "/placeholder-logo.png",
    city: "Bordeaux",
    employeeCount: 30,
  },
];

const upcomingSessions: UpcomingSession[] = [
  {
    id: "s1",
    courseTitle: "React Avancé — Patterns et Performance",
    organizationName: "TechCorp Formation",
    date: "2026-03-24",
    startTime: "09:00",
    endTime: "17:00",
    location: "Paris",
    type: "ONSITE",
  },
  {
    id: "s2",
    courseTitle: "React Avancé — Patterns et Performance",
    organizationName: "FormaPro Institute",
    date: "2026-03-28",
    startTime: "09:30",
    endTime: "17:30",
    location: "En ligne",
    type: "REMOTE",
  },
  {
    id: "s3",
    courseTitle: "Next.js 16 — Server Components et App Router",
    organizationName: "Digital Academy",
    date: "2026-04-02",
    startTime: "09:00",
    endTime: "17:00",
    location: "Bordeaux",
    type: "ONSITE",
  },
  {
    id: "s4",
    courseTitle: "Architecture microservices avec Node.js",
    organizationName: "TechCorp Formation",
    date: "2026-04-14",
    startTime: "10:00",
    endTime: "18:00",
    location: "En ligne",
    type: "REMOTE",
  },
];

const recentActivity: ActivityItem[] = [
  {
    id: "a1",
    type: "ENROLLMENT",
    message: "3 nouveaux inscrits à React Avancé — Patterns et Performance",
    timestamp: "2026-03-16T14:30:00",
  },
  {
    id: "a2",
    type: "REVIEW",
    message: "Nouvel avis 5/5 de Pierre Durand sur React Avancé",
    timestamp: "2026-03-16T10:15:00",
  },
  {
    id: "a3",
    type: "PAYMENT",
    message: "Paiement de 2 670 \u20AC re\u00E7u de TechCorp Formation",
    timestamp: "2026-03-15T16:45:00",
  },
  {
    id: "a4",
    type: "ENROLLMENT",
    message: "1 nouvel inscrit \u00E0 React Avanc\u00E9 via la marketplace",
    timestamp: "2026-03-15T09:20:00",
  },
  {
    id: "a5",
    type: "COURSE_PUBLISHED",
    message: "Votre formation Next.js 16 est en attente de validation",
    timestamp: "2026-03-14T11:00:00",
  },
  {
    id: "a6",
    type: "REVIEW",
    message: "Nouvel avis 4/5 de Marie Lefèvre sur React Avancé",
    timestamp: "2026-03-13T17:30:00",
  },
  {
    id: "a7",
    type: "PAYMENT",
    message: "Paiement de 890 \u20AC re\u00E7u via la marketplace",
    timestamp: "2026-03-12T14:00:00",
  },
];

const monthlyRevenueData: MonthlyRevenuePoint[] = [
  { month: "Jan", revenue: 3200, previousYear: 2800 },
  { month: "Fév", revenue: 4100, previousYear: 3200 },
  { month: "Mar", revenue: 3800, previousYear: 3500 },
  { month: "Avr", revenue: 5200, previousYear: 4100 },
  { month: "Mai", revenue: 4900, previousYear: 4300 },
  { month: "Jun", revenue: 5100, previousYear: 4600 },
  { month: "Jul", revenue: 4800, previousYear: 3900 },
  { month: "Aoû", revenue: 5600, previousYear: 4200 },
  { month: "Sep", revenue: 4200, previousYear: 3800 },
  { month: "Oct", revenue: 3900, previousYear: 3600 },
  { month: "Nov", revenue: 5100, previousYear: 4500 },
  { month: "Déc", revenue: 4350, previousYear: 3800 },
];

const trainerProfileStats: TrainerProfileStats = {
  profileViews: 800,
  profileClicks: 325,
  profileContacts: 38,
  totalCandidatures: 55,
};

const trainerAnnonces: Annonce[] = [
  {
    id: "an1",
    organizationName: "Digital X",
    organizationLogo: "/placeholder-logo.png",
    title: "Recherche Intervenant Intelligence Artificielle",
    specialty: "Intelligence Artificielle",
    departement: "69",
    status: "candidated",
  },
  {
    id: "an2",
    organizationName: "Digital X",
    organizationLogo: "/placeholder-logo.png",
    title: "Recherche Intervenant Pilotage Commercial",
    specialty: "No-code",
    departement: "69",
    status: "saved",
  },
  {
    id: "an3",
    organizationName: "FormaPro Institute",
    organizationLogo: "/placeholder-logo.png",
    title: "Formateur React & TypeScript confirmé",
    specialty: "React",
    departement: "75",
    status: "candidated",
  },
  {
    id: "an4",
    organizationName: "TechCorp Formation",
    organizationLogo: "/placeholder-logo.png",
    title: "Expert Node.js pour formation interne",
    specialty: "Node.js",
    departement: "92",
    status: "saved",
  },
];

export const availableAnnonces: Annonce[] = [
  {
    id: "av1",
    organizationName: "Digital College",
    organizationLogo: "/placeholder-logo.png",
    orgType: "École Supérieur",
    title: "Formateur Community Manager",
    specialty: "Communication",
    departement: "34",
    domains: ["Communication", "Community Management"],
    level: "Expert",
    interventionType: "Présentiel",
    dateStart: "2026-02-21",
    dateEnd: "2026-06-21",
    durationHours: 56,
    hourlyRate: 50,
  },
  {
    id: "av2",
    organizationName: "FormaPro Institute",
    organizationLogo: "/placeholder-logo.png",
    orgType: "Centre de Formation",
    title: "Formateur Excel & Power BI",
    specialty: "Bureautique",
    departement: "75",
    domains: ["Bureautique", "Data Visualisation"],
    level: "Confirmé",
    interventionType: "Distanciel",
    dateStart: "2026-04-01",
    dateEnd: "2026-07-31",
    durationHours: 35,
    hourlyRate: 45,
  },
  {
    id: "av3",
    organizationName: "TechCorp Formation",
    organizationLogo: "/placeholder-logo.png",
    orgType: "Organisme de Formation",
    title: "Intervenant Cybersécurité",
    specialty: "Cybersécurité",
    departement: "69",
    domains: ["Cybersécurité", "Réseau"],
    level: "Expert",
    interventionType: "Hybride",
    dateStart: "2026-03-15",
    dateEnd: "2026-09-15",
    durationHours: 70,
    hourlyRate: 65,
  },
  {
    id: "av4",
    organizationName: "Digital Academy",
    organizationLogo: "/placeholder-logo.png",
    orgType: "École Supérieur",
    title: "Formateur UX Design",
    specialty: "Design",
    departement: "33",
    domains: ["UX Design", "Figma", "Prototypage"],
    level: "Confirmé",
    interventionType: "Présentiel",
    dateStart: "2026-05-01",
    dateEnd: "2026-08-31",
    durationHours: 42,
    hourlyRate: 55,
  },
];

export const trainerSupportData: TrainerSupportData = {
  tickets: [
    {
      id: "tk1",
      subject: "Problème d'affichage sur mon profil",
      category: "technical",
      status: "in_progress",
      createdAt: "2026-03-10T09:00:00",
      lastReply: "2026-03-12T14:00:00",
      preview: "Bonjour, depuis hier mon profil n'affiche plus mes spécialités...",
    },
    {
      id: "tk2",
      subject: "Question sur ma facture de mars",
      category: "billing",
      status: "resolved",
      createdAt: "2026-03-05T10:30:00",
      lastReply: "2026-03-07T11:00:00",
      preview: "Je n'ai pas reçu ma facture pour le mois de mars...",
    },
    {
      id: "tk3",
      subject: "Impossible de modifier mes disponibilités",
      category: "account",
      status: "open",
      createdAt: "2026-03-16T16:00:00",
      preview: "Quand je clique sur enregistrer, rien ne se passe...",
    },
    {
      id: "tk4",
      subject: "Demande de renseignements plan Premium",
      category: "other",
      status: "closed",
      createdAt: "2026-02-28T08:00:00",
      lastReply: "2026-03-01T10:00:00",
      preview: "Bonjour, je souhaiterais en savoir plus sur les avantages...",
    },
  ],
  chatHistory: [
    {
      id: "cm1",
      from: "agent",
      content: "Bonjour Sophie ! Je suis votre assistant support Synext. Comment puis-je vous aider aujourd'hui ?",
      timestamp: "2026-03-17T09:00:00",
    },
    {
      id: "cm2",
      from: "user",
      content: "Bonjour, j'ai une question sur le fonctionnement des candidatures.",
      timestamp: "2026-03-17T09:01:00",
    },
    {
      id: "cm3",
      from: "agent",
      content: "Bien sûr ! Vous pouvez candidater à une annonce depuis l'onglet Annonce. Une fois candidatée, elle apparaît dans la section Suivi Candidature de votre tableau de bord.",
      timestamp: "2026-03-17T09:01:30",
    },
    {
      id: "cm4",
      from: "user",
      content: "Merci, c'est plus clair !",
      timestamp: "2026-03-17T09:02:00",
    },
  ],
  faq: [
    {
      question: "Comment candidater à une annonce ?",
      answer: "Rendez-vous dans l'onglet Annonce de votre dashboard. Recherchez une annonce qui correspond à votre profil, puis cliquez sur 'Découvrir l'annonce'. Vous pouvez ensuite postuler directement depuis la page de l'annonce. Votre candidature apparaîtra dans la section Suivi Candidature de votre tableau de bord.",
    },
    {
      question: "Comment modifier mon tarif horaire ?",
      answer: "Accédez à l'onglet Profil depuis la barre de navigation. Dans la section 'Informations générales', vous trouverez le champ Tarif horaire. Modifiez la valeur puis cliquez sur 'Enregistrer les modifications'.",
    },
    {
      question: "Comment gérer mes disponibilités ?",
      answer: "L'onglet Disponibilité vous permet de gérer vos disponibilités de trois façons : (1) en cliquant sur des jours dans le calendrier pour définir un statut, (2) en configurant des plages horaires récurrentes par jour de la semaine, (3) en renseignant vos préférences d'intervention (type, rayon géographique, durée).",
    },
    {
      question: "Quand suis-je payé pour une mission ?",
      answer: "Le paiement intervient sous 30 jours après la fin de la mission, une fois la formation validée par l'organisme. Vous recevrez un email de confirmation et pourrez retrouver la facture dans la section Abonnement de l'onglet Accès.",
    },
    {
      question: "Comment améliorer la visibilité de mon profil ?",
      answer: "Plusieurs actions augmentent votre visibilité : complétez à 100% votre profil (bio, spécialités, tarif, photo), activez l'option 'Profil public' dans Accès > Visibilité, soyez réactif aux annonces, et accumulez des avis positifs après chaque mission.",
    },
    {
      question: "Comment contacter un organisme qui m'a consulté ?",
      answer: "Actuellement, c'est l'organisme qui initie le contact depuis votre profil. Vous recevrez une notification dès qu'un organisme vous contacte. En passant au plan Premium, vous pouvez voir la liste des organismes qui ont consulté votre profil et leur envoyer un message en premier.",
    },
  ],
};

export const trainerAccountSettings: TrainerAccountSettings = {
  profilePublic: true,
  showHourlyRate: false,
  contactRestriction: "verified_only",
  twoFactorEnabled: false,
  activeSessions: [
    {
      id: "ses1",
      device: "MacBook Pro — Chrome",
      ip: "92.184.xx.xx",
      location: "Paris, France",
      lastSeen: "2026-03-17T20:00:00",
      current: true,
    },
    {
      id: "ses2",
      device: "iPhone 15 — Safari",
      ip: "92.184.xx.xx",
      location: "Paris, France",
      lastSeen: "2026-03-16T18:30:00",
      current: false,
    },
  ],
  notifications: {
    newAnnonce: true,
    newMessage: true,
    newCandidature: true,
    frequency: "daily",
  },
  plan: "free",
};

export const trainerAvailability: TrainerAvailability = {
  slots: [
    { id: "sl1", date: "2026-03-18", status: "available" },
    { id: "sl2", date: "2026-03-19", status: "available" },
    { id: "sl3", date: "2026-03-20", status: "on_mission" },
    { id: "sl4", date: "2026-03-21", status: "on_mission" },
    { id: "sl5", date: "2026-03-25", status: "unavailable", note: "Congés" },
    { id: "sl6", date: "2026-03-26", status: "unavailable", note: "Congés" },
    { id: "sl7", date: "2026-04-02", status: "tentative", note: "Sous réserve d'un autre engagement" },
    { id: "sl8", date: "2026-04-08", status: "available" },
    { id: "sl9", date: "2026-04-09", status: "available" },
    { id: "sl10", date: "2026-04-14", status: "on_mission" },
  ],
  weeklySchedule: [
    { id: "ws1", dayOfWeek: 1, startTime: "09:00", endTime: "17:00" },
    { id: "ws2", dayOfWeek: 3, startTime: "09:00", endTime: "17:00" },
    { id: "ws3", dayOfWeek: 5, startTime: "09:00", endTime: "12:00" },
  ],
  preferences: {
    interventionTypes: ["ONSITE", "REMOTE"],
    maxRadiusKm: 100,
    minMissionDays: 2,
    maxMissionDays: 10,
    availableFrom: "2026-03-18",
  },
};

export const trainerDashboardKPIs: TrainerDashboardKPIs = {
  profileStats: trainerProfileStats,
  annonces: trainerAnnonces,
  totalRevenue: 47250,
  activeCourses: 4,
  totalStudents: 312,
  averageRating: 4.8,
  monthlyRevenue: [3200, 4100, 3800, 5200, 4900, 5100, 4800, 5600, 4200, 3900, 5100, 4350],
  revenueTrend: 12.5,
  studentsTrend: 8.2,
  ratingTrend: 2.1,
  coursesTrend: 0,
  monthlyRevenueData,
  upcomingSessions,
  recentActivity,
};

const orgMonthlySpendingData: MonthlySpendingPoint[] = [
  { month: "Jan", spending: 8500, previousYear: 7200 },
  { month: "Fév", spending: 12000, previousYear: 9800 },
  { month: "Mar", spending: 9800, previousYear: 8500 },
  { month: "Avr", spending: 11200, previousYear: 9200 },
  { month: "Mai", spending: 10500, previousYear: 8800 },
  { month: "Jun", spending: 14200, previousYear: 11500 },
  { month: "Jul", spending: 13100, previousYear: 10200 },
  { month: "Aoû", spending: 9800, previousYear: 7600 },
  { month: "Sep", spending: 11500, previousYear: 9900 },
  { month: "Oct", spending: 12800, previousYear: 10800 },
  { month: "Nov", spending: 10200, previousYear: 9100 },
  { month: "Déc", spending: 14800, previousYear: 12400 },
];

const orgUpcomingTrainings: UpcomingTraining[] = [
  {
    id: "ot1",
    courseTitle: "React Avancé — Patterns et Performance",
    trainerName: "Sophie Martin",
    date: "2026-03-24",
    startTime: "09:00",
    endTime: "17:00",
    location: "Paris",
    type: "ONSITE",
    employeeCount: 8,
  },
  {
    id: "ot2",
    courseTitle: "Machine Learning pour les entreprises",
    trainerName: "Marc Dubois",
    date: "2026-03-31",
    startTime: "09:30",
    endTime: "17:30",
    location: "En ligne",
    type: "REMOTE",
    employeeCount: 12,
  },
  {
    id: "ot3",
    courseTitle: "Kubernetes en production",
    trainerName: "Thomas Leroy",
    date: "2026-04-07",
    startTime: "09:00",
    endTime: "17:00",
    location: "Paris",
    type: "ONSITE",
    employeeCount: 6,
  },
  {
    id: "ot4",
    courseTitle: "Leadership agile pour managers",
    trainerName: "Julien Moreau",
    date: "2026-04-14",
    startTime: "10:00",
    endTime: "18:00",
    location: "En ligne",
    type: "REMOTE",
    employeeCount: 15,
  },
];

const orgRecentActivity: ActivityItem[] = [
  {
    id: "oa1",
    type: "TRAINER_HIRED",
    message: "Sophie Martin a accepté la mission React Avancé",
    timestamp: "2026-03-16T15:00:00",
  },
  {
    id: "oa2",
    type: "TRAINING_COMPLETED",
    message: "Formation SEO technique terminée — 12 employés certifiés",
    timestamp: "2026-03-15T17:00:00",
  },
  {
    id: "oa3",
    type: "PAYMENT",
    message: "Facture de 4 450 \u20AC réglée pour Machine Learning",
    timestamp: "2026-03-15T10:30:00",
  },
  {
    id: "oa4",
    type: "ENROLLMENT",
    message: "5 employés inscrits à Kubernetes en production",
    timestamp: "2026-03-14T14:20:00",
  },
  {
    id: "oa5",
    type: "TRAINER_HIRED",
    message: "Thomas Leroy a accepté la mission Kubernetes",
    timestamp: "2026-03-13T11:45:00",
  },
  {
    id: "oa6",
    type: "TRAINING_COMPLETED",
    message: "Formation Design System terminée — 8 employés formés",
    timestamp: "2026-03-12T17:00:00",
  },
  {
    id: "oa7",
    type: "PAYMENT",
    message: "Facture de 7 800 \u20AC réglée pour Leadership agile",
    timestamp: "2026-03-11T09:15:00",
  },
];

export const organizationDashboardKPIs: OrganizationDashboardKPIs = {
  totalSpent: 128400,
  activeTrainers: 12,
  coursesCompleted: 34,
  employeesTrained: 186,
  monthlySpending: [8500, 12000, 9800, 11200, 10500, 14200, 13100, 9800, 11500, 12800, 10200, 14800],
  spentTrend: 15.3,
  trainersTrend: 9.1,
  coursesTrend: 6.3,
  employeesTrend: 12.8,
  monthlySpendingData: orgMonthlySpendingData,
  upcomingTrainings: orgUpcomingTrainings,
  recentActivity: orgRecentActivity,
};
